x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  qtbotbase:
    << : *restart_policy
    container_name: qtbotbase
    image: ghcr.io/onerandomusername/qtbotbase:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true

    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy

    env_file:
      - .env

    volumes:
      - ./qtbotbase:/bot/qtbotbase
      - ./qtbotbase.db:/bot/qtbotbase.db
